insert into tb_categoria (descricao) values ('Fixo');
insert into tb_categoria (descricao) values ('Nubank');
insert into tb_categoria (descricao) values ('Itaucard');
insert into tb_categoria (descricao) values ('Will');
insert into tb_categoria (descricao) values ('Casas bahias');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Salário',                    5000.84, TRUE,  1, 'ENTRADA', '2024-02-27');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Compra de mantimentos',     -1578.50, TRUE,  1, 'SAIDA', '2024-02-27');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Pagamento de conta de luz', -150.20,  TRUE,  1, 'SAIDA', '2024-02-26');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Almoço com amigos',         -90,      FALSE, 1, 'SAIDA', '2024-02-25');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Combustível para o carro',  -60.75,   FALSE, 1, 'SAIDA', '2024-02-24');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Cinema com a família',      -45.30,   FALSE, 2, 'SAIDA', '2024-02-23');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Jantar romântico',          -120.90,  TRUE,  2, 'SAIDA', '2024-02-22');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Roupas novas',              -200,     FALSE, 2, 'SAIDA', '2024-02-21');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Conserto do celular',       -5580,    FALSE, 2, 'SAIDA', '2024-02-20');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Presente de aniversário',   -30.50,   TRUE,  2, 'SAIDA', '2024-02-19');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Assinatura de streaming',   -12.99,   FALSE, 3, 'SAIDA', '2024-02-18');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Lanche rápido',             -8.75,    TRUE,  3, 'SAIDA', '2024-02-17');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Livro novo',                -25,      FALSE, 3, 'SAIDA', '2024-02-16');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Café da manhã',             -15.30,   FALSE, 4, 'SAIDA', '2024-02-15');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Taxa bancária',             -7.50,    TRUE,  4, 'SAIDA', '2024-02-14');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Ingresso para show',        -70,      FALSE, 4, 'SAIDA', '2024-02-13');
insert into tb_movimentacao (descricao, valor, pago, categoria_id, tipo, data_inclusao) values ('Manutenção do computador',  -150,     TRUE,  4, 'SAIDA', '2024-02-12');